
FROM openjdk:8u181
ADD target/spring-boot-rest-example-0.0.1-SNAPSHOT.jar /opt/spring-boot-rest-example-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/opt/spring-boot-rest-example-0.0.1-SNAPSHOT.jar"]